version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/opt/data:/opt/data'
    ports:
      - '8080:8080'
    depends_on:
      - cache
      - database
    links:
      - cache
      - database
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: 100MB
        max-file: '3'
    environment:
      NODE_ENV: production
      DOCKER: 'true'
      PRODUCT_URL: 'https://radinfluencer.com'
      PRODUCT_NAME: RadFeed
      PRODUCT_AUTHOR: RadIntelligence
      DATABASE_URI: 'mongodb://database/rad_feed_staging'
      CACHE_URI: 'redis://cache:6379'
      JWT_SECRET: UdSXHuC+/KchK5Js3o7mwByAQUs8sohwZUg4AFKAui1RlfXTzcoSY4GqeIgNHO6ZvRX2sgZNzITJ/0HsrMwEjNgPK7ipQTu5/SLBTJyqAbhLrHM7heTtphCQZMqqXKJZxlvQh/UeGmoa+g2lxG0vUSVEFiaa37ucSYITw1EsYh5iWf6dhZkwW3MUJJvkQdlu/8RrHB4/bvhk00oKCyTfjRxInNSqJQZuoU3c1A==
      API_PORT: 8080
      STREAM_API_BASE_URL: 'https://us-east-api.stream-io-api.com/api/v1.0/'
      STREAM_APP_ID: 61987
      STREAM_API_KEY: gxef8x2sm67t
      STREAM_API_SECRET: fc6kmy9dsj2rxdm4kxz73hdjty7e245fhyegfknugygyk3nc7umst5mwg4xgvxhk
      ALGOLIA_WRITE_KEY: 565915075aa73b77aa45ee6c21b76fb1
  cache:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - backend
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100MB
        max-file: '3'
  database:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: 100MB
        max-file: '3'
networks:
  backend: null
